state:
  type: joint_state_controller/JointStateController
  publish_rate: 50

dof:
  position:
    '1':
      type: position_controllers/JointPositionController
      joint: Axis_1_joint
    '2':
      type: position_controllers/JointPositionController
      joint: Axis_2_joint
    '3':
      type: position_controllers/JointPositionController
      joint: Axis_3_joint
    '4':
      type: position_controllers/JointPositionController
      joint: Axis_4_joint
    '5':
      type: position_controllers/JointPositionController
      joint: Axis_5_joint
    '6':
      type: position_controllers/JointPositionController
      joint: Axis_6_joint
group:
  position:
    first3:
      type: position_controllers/JointGroupPositionController
      joints:
        - Axis_1_joint
        - Axis_2_joint
        - Axis_3_joint
    arm:
      type: position_controllers/JointGroupPositionController
      joints:
        - Axis_1_joint
        - Axis_2_joint
        - Axis_3_joint
        - Axis_4_joint
        - Axis_5_joint
        - Axis_6_joint
trajectory:
  arm:
    type: position_controllers/JointTrajectoryController
    joints:
      - Axis_1_joint
      - Axis_2_joint
      - Axis_3_joint
      - Axis_4_joint
      - Axis_5_joint
      - Axis_6_joint
