generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 0.01
  
hardware_interface:
  joints:
    - Axis_1_joint
    - Axis_2_joint
    - Axis_3_joint
    - Axis_4_joint
    - Axis_5_joint
    - Axis_6_joint

