controller_list:
  - name: bartender/control/trajectory/arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Axis_1_joint
      - Axis_2_joint
      - Axis_3_joint
      - Axis_4_joint
      - Axis_5_joint
      - Axis_6_joint
